export const ignorableAbilities = new Set([
  "Aroma Veil",
  "Battle Armor",
  "Big Pecks",
  "Bulletproof",
  "Clear Body",
  "Contrary",
  "Damp",
  "Dazzling",
  "Disguise",
  "Dry Skin",
  "Filter",
  "Flash Fire",
  "Flower Gift",
  "Fluffy",
  "Flower Veil",
  "Friend Guard",
  "Fur Coat",
  "Heatproof",
  "Heavy Metal",
  "Hyper Cutter",
  "Immunity",
  "Inner Focus",
  "Insomnia",
  "Keen Eye",
  "Leaf Guard",
  "Levitate",
  "Light Metal",
  "Lightning Rod",
  "Limber",
  "Magic Bounce",
  "Magma Armor",
  "Marvel Scale",
  "Motor Drive",
  "Multiscale",
  "Oblivious",
  "Overcoat",
  "Own Tempo",
  "Queenly Majesty",
  "Sand Veil",
  "Sap Sipper",
  "Shell Armor",
  "Shield Dust",
  "Simple",
  "Snow Cloak",
  "Solid Rock",
  "Soundproof",
  "Sticky Hold",
  "Storm Drain",
  "Sturdy",
  "Suction Cups",
  "Sweet Veil",
  "Tangled Feet",
  "Telepathy",
  "Thick Fat",
  "Unaware",
  "Vital Spirit",
  "Volt Absorb",
  "Water Absorb",
  "Water Bubble",
  "Water Veil",
  "White Smoke",
  "Wonder Guard",
  "Wonder Skin"
]);

export const requiredItems = new Map(
  Object.entries({
    // don't exclude plates & orbs as those affect damage
    // Genesect
    "Genesect-Douse": "Douse Drive",
    "Genesect-Shock": "Shock Drive",
    "Genesect-Burn": "Burn Drive",
    "Genesect-Chill": "Chill Drive",
    // Megas
    "Abomasnow-Mega": "Abomasite",
    "Absol-Mega": "Absolite",
    "Aerodactyl-Mega": "Aerodactylite",
    "Aggron-Mega": "Aggronite",
    "Alakazam-Mega": "Alakazite",
    "Altaria-Mega": "Altarianite",
    "Ampharos-Mega": "Ampharosite",
    "Audino-Mega": "Audinite",
    "Banette-Mega": "Banettite",
    "Beedrill-Mega": "Beedrillite",
    "Blastoise-Mega": "Blastoisinite",
    "Blaziken-Mega": "Blazikenite",
    "Camerupt-Mega": "Cameruptite",
    "Charizard-Mega-X": "Charizardite X",
    "Charizard-Mega-Y": "Charizardite Y",
    "Diancie-Mega": "Diancite",
    "Gallade-Mega": "Galladite",
    "Garchomp-Mega": "Garchompite",
    "Gardevoir-Mega": "Gardevoirite",
    "Gengar-Mega": "Gengarite",
    "Glalie-Mega": "Glalitite",
    "Gyarados-Mega": "Gyaradosite",
    "Heracross-Mega": "Heracronite",
    "Houndoom-Mega": "Houndoominite",
    "Kangaskhan-Mega": "Kangaskhanite",
    "Latias-Mega": "Latiasite",
    "Latios-Mega": "Latiosite",
    "Lopunny-Mega": "Lopunnity",
    "Lucario-Mega": "Lucarionite",
    "Manectric-Mega": "Manectite",
    "Mawile-Mega": "Mawilite",
    "Medicham-Mega": "Medichamite",
    "Metagross-Mega": "Metagrossite",
    "Mewtwo-Mega-X": "Mewtwonite X",
    "Mewtwo-Mega-Y": "Mewtwonite Y",
    "Pidgeot-Mega": "Pidgeotite",
    "Pinsir-Mega": "Pinsirite",
    "Sableye-Mega": "Sablenite",
    "Salamence-Mega": "Salamencite",
    "Sceptile-Mega": "Sceptilite",
    "Scizor-Mega": "Scizorite",
    "Sharpedo-Mega": "Sharpedonite",
    "Slowbro-Mega": "Slowbronite",
    "Steelix-Mega": "Steelixite",
    "Swampert-Mega": "Swampertite",
    "Tyranitar-Mega": "Tyranitarite",
    "Venusaur-Mega": "Venusaurite",
    // Primals
    "Groudon-Primal": "Red Orb",
    "Kyogre-Primal": "Blue Orb",
    // Silvally
    "Silvally-Bug": "Bug Memory",
    "Silvally-Dark": "Dark Memory",
    "Silvally-Dragon": "Dragon Memory",
    "Silvally-Electric": "Electric Memory",
    "Silvally-Fairy": "Fairy Memory",
    "Silvally-Fighting": "Fighting Memory",
    "Silvally-Fire": "Fire Memory",
    "Silvally-Flying": "Flying Memory",
    "Silvally-Ghost": "Ghost Memory",
    "Silvally-Grass": "Grass Memory",
    "Silvally-Ground": "Ground Memory",
    "Silvally-Ice": "Ice Memory",
    "Silvally-Poison": "Poison Memory",
    "Silvally-Psychic": "Psychic Memory",
    "Silvally-Rock": "Rock Memory",
    "Silvally-Steel": "Steel Memory",
    "Silvally-Water": "Water Memory"
  })
);
